apiVersion: v1
kind: ConfigMap
metadata:
  name: recording-api-config
  namespace: livekit
data:
  LIVEKIT_URL: "wss://livekit.market.implica.ru"
  S3_ENDPOINT: "http://minio.minio.svc.cluster.local:9000"
  S3_BUCKET: "livekit-recordings"
