apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recording-api
  namespace: livekit
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - api.market.implica.ru
    secretName: recording-api-tls
  rules:
  - host: api.market.implica.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: recording-api
            port:
              number: 3000
