apiVersion: v1
kind: Secret
metadata:
  name: recording-api-secret
  namespace: livekit
type: Opaque
stringData:
  LIVEKIT_API_KEY: "devkey"
  LIVEKIT_API_SECRET: "secret123456789012345678901234567890"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "MinioAdmin2026!"
