apiVersion: v1
kind: Service
metadata:
  name: recording-api
  namespace: livekit
  labels:
    app: recording-api
spec:
  type: ClusterIP
  selector:
    app: recording-api
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
